version: '3.8'

services:
  novelai-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novelai-ui
    restart: always
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
